---
timezone: Australia/Brisbane

# minima
author: Alex Cruice
description: rhymes with juice
disqus:
  shortname: atcruice
# email: alex.cruice@gmail.com
# facebook_username: atcruice
github_username: atcruice
header_pages: []
lang: en-AU
# linkedin_username: atcruice
minima:
  date_format: "%-d %B %Y"
rss: false
show_excerpts: true
theme: minima
title: cruice.net
# twitter_username: atcruice

# jekyll-seo-tag
facebook:
  publisher: atcruice
logo: /assets/ulam_spiral_5.svg
social:
  links:
    - "https://github.com/atcruice"
    - "https://www.facebook.com/atcruice"
    - "https://www.linkedin.com/in/atcruice"
    - "https://www.twitter.com/atcruice"
twitter:
  card: summary
  username: atcruice

exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "bin/"
  - "nix/"
  - "shell.nix"
  - "tags"
